// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXQiXKHCcQ-cATAGJcHhuXBvL57hlnh5s',
    appId: '1:234586759455:web:19c01c63c273e1e011502a',
    messagingSenderId: '234586759455',
    projectId: 'flowerly-e5b70',
    authDomain: 'flowerly-e5b70.firebaseapp.com',
    storageBucket: 'flowerly-e5b70.firebasestorage.app',
    measurementId: 'G-XFVZV65QJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-qb4xSdGd593t9qK5E6XYHNeszefW09A',
    appId: '1:234586759455:android:017320ef5b73152211502a',
    messagingSenderId: '234586759455',
    projectId: 'flowerly-e5b70',
    storageBucket: 'flowerly-e5b70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXaAtR-FL55mcgs3k9odaMfyiyHR95ppA',
    appId: '1:234586759455:ios:353bc1783656644f11502a',
    messagingSenderId: '234586759455',
    projectId: 'flowerly-e5b70',
    storageBucket: 'flowerly-e5b70.firebasestorage.app',
    iosBundleId: 'com.example.flowerllyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXaAtR-FL55mcgs3k9odaMfyiyHR95ppA',
    appId: '1:234586759455:ios:353bc1783656644f11502a',
    messagingSenderId: '234586759455',
    projectId: 'flowerly-e5b70',
    storageBucket: 'flowerly-e5b70.firebasestorage.app',
    iosBundleId: 'com.example.flowerllyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXQiXKHCcQ-cATAGJcHhuXBvL57hlnh5s',
    appId: '1:234586759455:web:6ba7079ce16e28fb11502a',
    messagingSenderId: '234586759455',
    projectId: 'flowerly-e5b70',
    authDomain: 'flowerly-e5b70.firebaseapp.com',
    storageBucket: 'flowerly-e5b70.firebasestorage.app',
    measurementId: 'G-VNWGG76B24',
  );
}
